baseURL = "https://tevoza.github.io/adamncollection/"
languageCode = "en-us"
title = "adamncollection"
enableRobotsTXT = true

[params]
  author = "Adam"
  description = "Notes on software, thoughts, and food."
  githubRepo = "https://github.com/tevoza/adamncollection"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 2

  [[menu.main]]
    name = "Thoughts"
    url = "/thoughts/"
    weight = 3

  [[menu.main]]
    name = "Food"
    url = "/food/"
    weight = 4

  [[menu.main]]
    name = "Book Reviews"
    url = "/book-reviews/"
    weight = 5

  [[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 6

[taxonomies]
  tag = "tags"
